version: '3'

services:
  my_app_1:
    container_name: my_app_1
    image: alpine:latest
    ports:
      - "8090:8080"
  my_app_2:
    container_name: my_app_2
    image: alpine:latest
    ports:
      - "8080:8080"
  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.19-alpine
    environment:
      - DOMAIN
    entrypoint: ["/entrypoint.sh"]
    command: "/bin/sh -c 'nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
    volumes:
      - ./nginx/public:/var/www/html
      - ./nginx/conf.d.http:/etc/nginx/templates
      - ./nginx/entrypoint.sh:/entrypoint.sh