version: "3.8"
services:
    nginx: 
        image: nginx:latest
        restart: always
        volumes:
            - ./public:/var/www/html
            - ./nginx/conf.d.http:/etc/nginx/conf.d

        ports:
            - 80:80


